"""JLPT N2 kanji seed data.

Extracted from the Mensura Media reference chart
``japanese/jp_kanji/reference_chart_kanji_n2.pdf`` in the companion
`language-learning <https://github.com/MensuraMedia/language-learning>`_ repository,
which is the authority for this project's character data.

On'yomi are written in katakana and kun'yomi in hiragana, matching the
convention fixed by the content model. The charts give readings in wapuro
romaji; conversion to kana is mechanical and every reading was verified by
converting back and comparing. Where a chart states only one reading it does
not say which kind it is, so the field is chosen from a lexicon built from the
664 explicit on/kun pairs across all five levels — a held-out test of that
rule against the N1 pairs scored 94.6%. **Kanji cards are graded on the
meaning**, so a mislabelled reading affects the reference rows on the card
back and nothing that is scored.

Kun'yomi are the chart's whole-word readings; okurigana are not bracketed as
they are in :mod:`.kanji_n5`. Stroke counts are not in the charts and are left
unset.
"""

from __future__ import annotations

from ..models import CharacterSeed

__all__ = ["KANJI_N2"]


def _k(
    glyph: str,
    meaning: str,
    onyomi: str | None,
    kunyomi: str | None,
    category: str | None,
) -> CharacterSeed:
    """Build a N2 kanji seed with the shared script/level fields filled in."""
    return CharacterSeed(
        glyph=glyph,
        script="kanji",
        meaning=meaning,
        onyomi=onyomi,
        kunyomi=kunyomi,
        jlpt_level="N2",
        category=category,
    )


#: 236 characters, in chart order.
KANJI_N2: tuple[CharacterSeed, ...] = (
    _k("党", "party/faction", "トウ", None, "Government & Administration"),
    _k("総", "general/whole", "ソウ", None, "Government & Administration"),
    _k("府", "govt office", "フ", None, "Government & Administration"),
    _k("省", "ministry/conserve", "ショウ", None, "Government & Administration"),
    _k("庁", "government office", "チョウ", None, "Government & Administration"),
    _k("署", "signature", "ショ", None, "Government & Administration"),
    _k("委", "committee/entrust", "イ", None, "Government & Administration"),
    _k("各", "each/every", "カク", None, "Government & Administration"),
    _k("改", "reform/change", "カイ", None, "Government & Administration"),
    _k("副", "vice/duplicate", None, "ふく", "Government & Administration"),
    _k("令", "orders/command", "レイ", None, "Government & Administration"),
    _k("旧", "old times/former", "キュウ", None, "Government & Administration"),
    _k("再", "again/twice", "サイ", None, "Government & Administration"),
    _k("州", "state/province", "シュウ", None, "Government & Administration"),
    _k("欧", "Europe", "オウ", None, "Government & Administration"),
    _k("諸", "various/many", "ショ", None, "Government & Administration"),
    _k("勢", "forces/energy", "セイ", None, "Government & Administration"),
    _k("録", "record", "ロク", None, "Government & Administration"),
    _k("営", "occupation/conduct", "エイ", None, "Government & Administration"),
    _k("減", "decrease/reduce", "ゲン", None, "Government & Administration"),
    _k("承", "acquiesce/hear", "ショウ", None, "Law, Order & Procedure"),
    _k("順", "obey/order/turn", "ジュン", None, "Law, Order & Procedure"),
    _k("了", "complete/finish", "リョウ", None, "Law, Order & Procedure"),
    _k("封", "seal/closing", "フウ", None, "Law, Order & Procedure"),
    _k("簡", "simplicity/brevity", "カン", None, "Law, Order & Procedure"),
    _k("章", "badge/chapter", "ショウ", None, "Law, Order & Procedure"),
    _k("訓", "instruction", "クン", None, "Law, Order & Procedure"),
    _k("課", "chapter/lesson", "カ", None, "Law, Order & Procedure"),
    _k("版", "class printing block", "ハン", None, "Law, Order & Procedure"),
    _k("算", "calculate/number", "サン", None, "Law, Order & Procedure"),
    _k("般", "carrier/all", "ハン", None, "Law, Order & Procedure"),
    _k("将", "leader/commander", "ショウ", None, "Military & Conflict"),
    _k("爆", "bomb/burst open", "バク", None, "Military & Conflict"),
    _k("暴", "outburst/violence", "ボウ", None, "Military & Conflict"),
    _k("乱", "riot/disorder/disturb", "ラン", None, "Military & Conflict"),
    _k("逆", "inverted/reverse", "ギャク", None, "Military & Conflict"),
    _k("停", "halt/stopping", "テイ", None, "Military & Conflict"),
    _k("駐", "stop-over/reside", "チュウ", None, "Military & Conflict"),
    _k("占", "fortune-telling", "セン", None, "Military & Conflict"),
    _k("固", "harden/set/clot", "コ", None, "Military & Conflict"),
    _k("賞", "prize/reward", "ショウ", None, "Economy & Commerce"),
    _k("販", "marketing/sell", "ハン", None, "Economy & Commerce"),
    _k("貯", "savings/store/lay", "チョ", None, "Economy & Commerce"),
    _k("募", "recruit/campaign", "ボ", None, "Economy & Commerce"),
    _k("替", "exchange/spare", "タイ", None, "Economy & Commerce"),
    _k("預", "deposit/custody", "ヨ", None, "Economy & Commerce"),
    _k("雇", "employ/hire", "コ", None, "Economy & Commerce"),
    _k("倍", "double/twice/times", "バイ", None, "Economy & Commerce"),
    _k("均", "level/average", "キン", None, "Economy & Commerce"),
    _k("億", "hundred million", "オク", None, "Economy & Commerce"),
    _k("低", "lower/short/humble", "テイ", None, "Economy & Commerce"),
    _k("復", "restore/return", None, "ふく", "Economy & Commerce"),
    _k("専", "specialty/solely", "セン", None, "Economy & Commerce"),
    _k("昇", "rise up", "ショウ", None, "Economy & Commerce"),
    _k("講", "lecture/club", "コウ", None, "Economy & Commerce"),
    _k("個", "individual/counter", "コ", None, "Economy & Commerce"),
    _k("栄", "flourish/prosperity", "エイ", None, "Economy & Commerce"),
    _k("券", "ticket", "ケン", None, "Economy & Commerce"),
    _k("籍", "enroll/membership", "セキ", None, "Economy & Commerce"),
    _k("枚", "sheet", "マイ", None, "Economy & Commerce"),
    _k("郵", "mail", "ユウ", None, "Economy & Commerce"),
    _k("脳", "brain/memory", "ノウ", None, "Science & Measurement"),
    _k("極", "poles/end/very", "キョク", None, "Science & Measurement"),
    _k("測", "fathom/measure", "ソク", None, "Science & Measurement"),
    _k("像", "statue/picture", "ゾウ", None, "Science & Measurement"),
    _k("液", "fluid/liquid/juice", "エキ", None, "Science & Measurement"),
    _k("溶", "melt/dissolve/thaw", "ヨウ", None, "Science & Measurement"),
    _k("鉱", "mineral/ore", "コウ", None, "Science & Measurement"),
    _k("丸", "round/full/pills", None, "まる", "Science & Measurement"),
    _k("湾", "gulf/bay/inlet", "ワン", None, "Science & Measurement"),
    _k("秒", "second (time)", "ビョウ", None, "Science & Measurement"),
    _k("層", "stratum/social", "ソウ", None, "Science & Measurement"),
    _k("普", "universal/wide", "フ", None, "Science & Measurement"),
    _k("超", "transcend/super", "チョウ", None, "Science & Measurement"),
    _k("鋭", "pointed/sharpness", "エイ", None, "Science & Measurement"),
    _k("零", "zero/spill/overflow", "レイ", None, "Science & Measurement"),
    _k("薄", "dilute/thin/weak", "ハク", None, "Science & Measurement"),
    _k("濃", "concentrated/thick", "ノウ", None, "Science & Measurement"),
    _k("鈍", "dull/slow/foolish", "ドン", None, "Science & Measurement"),
    _k("療", "heal/cure", "リョウ", None, "Body & Medicine"),
    _k("齢", "age", "レイ", None, "Body & Medicine"),
    _k("浴", "bathe", "ヨク", None, "Body & Medicine"),
    _k("肩", "shoulder", "ケン", None, "Body & Medicine"),
    _k("膚", "skin/body/grain", "フ", None, "Body & Medicine"),
    _k("胃", "stomach/paunch", "イ", None, "Body & Medicine"),
    _k("脂", "fat/grease/tallow/tar", "シ", None, "Body & Medicine"),
    _k("鼻", "nose/snout", "ビ", None, "Body & Medicine"),
    _k("汗", "sweat/perspire", "カン", None, "Body & Medicine"),
    _k("涙", "tears/sympathy", "ルイ", None, "Body & Medicine"),
    _k("悩", "trouble/worry", "ノウ", None, "Body & Medicine"),
    _k("岸", "beach/shore", "ガン", None, "Nature & Landscape"),
    _k("河", "river", "カ", None, "Nature & Landscape"),
    _k("岩", "boulder/rock", "ガン", None, "Nature & Landscape"),
    _k("坂", "slope/incline/hill", "ハン", None, "Nature & Landscape"),
    _k("泉", "spring/fountain", "セン", None, "Nature & Landscape"),
    _k("郊", "outskirts/suburbs", "コウ", None, "Nature & Landscape"),
    _k("城", "castle", "ジョウ", None, "Nature & Landscape"),
    _k("永", "eternity/long", "エイ", None, "Nature & Landscape"),
    _k("宇", "eaves/roof/heaven", "ウ", None, "Nature & Landscape"),
    _k("巨", "gigantic/big/large", "キョ", None, "Nature & Landscape"),
    _k("希", "hope/rare/few", "キ", None, "Nature & Landscape"),
    _k("埋", "in bury/be filled up", "マイ", None, "Nature & Landscape"),
    _k("震", "quake/shake", "シン", None, "Weather & Elements"),
    _k("凍", "frozen/congeal", "トウ", None, "Weather & Elements"),
    _k("曇", "cloudy weather", "ドン", None, "Weather & Elements"),
    _k("雲", "cloud", "ウン", None, "Weather & Elements"),
    _k("沈", "sink/subside", "チン", None, "Weather & Elements"),
    _k("沸", "seethe/boil/ferment", "フツ", None, "Weather & Elements"),
    _k("燥", "parch/dry", "ソウ", None, "Weather & Elements"),
    _k("滴", "drip/drop", "テキ", None, "Weather & Elements"),
    _k("泥", "mud/mire", "デイ", None, "Weather & Elements"),
    _k("灰", "ashes/cremate", "カイ", None, "Weather & Elements"),
    _k("炭", "charcoal/coal", "タン", None, "Weather & Elements"),
    _k("灯", "lamp/light", "トウ", None, "Weather & Elements"),
    _k("燃", "burn/blaze/glow", "ネン", None, "Weather & Elements"),
    _k("銅", "copper", "ドウ", None, "Weather & Elements"),
    _k("菜", "vegetable/side dish", "サイ", None, "Plants & Agriculture"),
    _k("枝", "bough/branch/twig", "シ", None, "Plants & Agriculture"),
    _k("麦", "barley/wheat", "バク", None, "Plants & Agriculture"),
    _k("耕", "till/plow/cultivate", "コウ", None, "Plants & Agriculture"),
    _k("咲", "blossom/bloom", "ショウ", None, "Plants & Agriculture"),
    _k("竹", "bamboo", "チク", None, "Plants & Agriculture"),
    _k("植", "plant", "ショク", None, "Plants & Agriculture"),
    _k("緑", "green", "リョク", None, "Plants & Agriculture"),
    _k("枯", "wither/die/dry up", "コ", None, "Plants & Agriculture"),
    _k("粒", "grains/drop", "リュウ", None, "Plants & Agriculture"),
    _k("菓", "candy/cakes/fruit", "カ", None, "Plants & Agriculture"),
    _k("卵", "egg/ovum/spawn", "ラン", None, "Animals & Living Things"),
    _k("貝", "shellfish", "バイ", None, "Animals & Living Things"),
    _k("匹", "equal", "ヒツ", None, "Animals & Living Things"),
    _k("畜", "up livestock", "チク", None, "Animals & Living Things"),
    _k("群", "flock/group/crowd", "グン", None, "Animals & Living Things"),
    _k("珍", "rare/curious/strange", "チン", None, "Animals & Living Things"),
    _k("漁", "fishing/fishery", "ギョ", None, "Animals & Living Things"),
    _k("隻", "vessels", "セキ", None, "Animals & Living Things"),
    _k("油", "oil/fat", "ユ", None, "Food & Cooking"),
    _k("塩", "salt", "エン", None, "Food & Cooking"),
    _k("湯", "hot water/bath", "トウ", None, "Food & Cooking"),
    _k("粉", "flour/powder/dust", "フン", None, "Food & Cooking"),
    _k("缶", "for tin can/container", "カン", None, "Food & Cooking"),
    _k("瓶", "bottle/vial/jar", None, "びん", "Food & Cooking"),
    _k("皿", "dish/a helping/plate", "ベイ", None, "Food & Cooking"),
    _k("甘", "sweet/coax/pamper", "カン", None, "Food & Cooking"),
    _k("香", "incense/smell", "コウ", None, "Food & Cooking"),
    _k("召", "seduce/call/send", "ショウ", None, "Food & Cooking"),
    _k("焼", "bake/burning", "ショウ", None, "Food & Cooking"),
    _k("砂", "sand", "サ", None, "Food & Cooking"),
    _k("棒", "rod/stick/cane/pole", "ボウ", None, "Food & Cooking"),
    _k("乳", "milk/breasts", "ニュウ", None, "Food & Cooking"),
    _k("喫", "consume/eat/drink", "キツ", None, "Food & Cooking"),
    _k("辛", "spicy/bitter/hot", "シン", None, "Food & Cooking"),
    _k("机", "desk/table", "キ", None, "Home, Objects & Materials"),
    _k("筒", "cylinder/pipe/tube", "トウ", None, "Home, Objects & Materials"),
    _k("畳", "tatami mat/fold", "ジョウ", None, "Home, Objects & Materials"),
    _k("帽", "cap/headgear", "ボウ", None, "Home, Objects & Materials"),
    _k("糸", "thread", "シ", None, "Home, Objects & Materials"),
    _k("綿", "cotton", "メン", None, "Home, Objects & Materials"),
    _k("戸", "door", "コ", None, "Home, Objects & Materials"),
    _k("軒", "counter for houses", "ケン", None, "Home, Objects & Materials"),
    _k("庫", "warehouse", "コ", None, "Home, Objects & Materials"),
    _k("材", "lumber/timber", "ザイ", None, "Home, Objects & Materials"),
    _k("宝", "treasure/wealth", "ホウ", None, "Home, Objects & Materials"),
    _k("包", "wrap/pack up/cover", "ホウ", None, "Home, Objects & Materials"),
    _k("帯", "sash/belt/zone", "タイ", None, "Home, Objects & Materials"),
    _k("塗", "paint/plaster/daub", "ト", None, "Home, Objects & Materials"),
    _k("濯", "laundry/wash/rinse", "タク", None, "Home, Objects & Materials"),
    _k("掃", "sweep/brush", "ソウ", None, "Home, Objects & Materials"),
    _k("塔", "pagoda/tower", "トウ", None, "Home, Objects & Materials"),
    _k("隅", "corner/nook", "グウ", None, "Home, Objects & Materials"),
    _k("軟", "soft", "ナン", None, "Home, Objects & Materials"),
    _k("蔵", "storehouse/possess", "ゾウ", None, "Home, Objects & Materials"),
    _k("玉", "jewel/ball", "ギョク", None, "Home, Objects & Materials"),
    _k("舟", "boat/ship", "シュウ", None, "Home, Objects & Materials"),
    _k("詞", "part of speech", "シ", None, "Language, Arts & Media"),
    _k("編", "compilation/edit", "ヘン", None, "Language, Arts & Media"),
    _k("誌", "document/records", "シ", None, "Language, Arts & Media"),
    _k("刊", "publish/carve", "カン", None, "Language, Arts & Media"),
    _k("巻", "scroll/volume/book", "カン", None, "Language, Arts & Media"),
    _k("冊", "tome", "サツ", None, "Language, Arts & Media"),
    _k("劇", "drama/play", "ゲキ", None, "Language, Arts & Media"),
    _k("芸", "art/craft", "ゲイ", None, "Language, Arts & Media"),
    _k("踊", "jump/dance/leap", "ヨウ", None, "Language, Arts & Media"),
    _k("筆", "writing brush", "ヒツ", None, "Language, Arts & Media"),
    _k("刷", "printing/print", "サツ", None, "Language, Arts & Media"),
    _k("磨", "grind/polish/scour", None, "ま", "Language, Arts & Media"),
    _k("築", "fabricate/build", "チク", None, "Language, Arts & Media"),
    _k("績", "exploits", "セキ", None, "Language, Arts & Media"),
    _k("跡", "tracks/mark", "セキ", None, "Language, Arts & Media"),
    _k("紅", "crimson/deep red", "コウ", None, "Language, Arts & Media"),
    _k("仲", "go-between", "チュウ", None, "People & Relationships"),
    _k("童", "juvenile/child", "ドウ", None, "People & Relationships"),
    _k("姓", "surname", "セイ", None, "People & Relationships"),
    _k("臣", "retainer/subject", "シン", None, "People & Relationships"),
    _k("殿", "Mr./hall/mansion", "デン", None, "People & Relationships"),
    _k("賢", "intelligent/wise", "ケン", None, "People & Relationships"),
    _k("尊", "revered/valuable", "ソン", None, "People & Relationships"),
    _k("柔", "tender/weakness", "ジュウ", None, "People & Relationships"),
    _k("純", "genuine/purity", "ジュン", None, "People & Relationships"),
    _k("児", "newborn/child", "ジ", None, "People & Relationships"),
    _k("敬", "awe/respect/honor", "ケイ", None, "People & Relationships"),
    _k("勇", "courage/bravery", "ユウ", None, "People & Relationships"),
    _k("孫", "grandchild", "ソン", None, "People & Relationships"),
    _k("伺", "pay respects/visit", "シ", None, "People & Relationships"),
    _k("拝", "worship/adore", "ハイ", None, "People & Relationships"),
    _k("祈", "pray/wish", "キ", None, "People & Relationships"),
    _k("快", "cheerful/pleasant", "カイ", None, "Actions & Abstract Concepts"),
    _k("憎", "hate/detest", "ゾウ", None, "Actions & Abstract Concepts"),
    _k("荒", "laid waste/rough", "コウ", None, "Actions & Abstract Concepts"),
    _k("叫", "shout/exclaim/yell", "キョウ", None, "Actions & Abstract Concepts"),
    _k("傾", "lean/incline/tilt", "ケイ", None, "Actions & Abstract Concepts"),
    _k("絡", "entwine/coil", "ラク", None, "Actions & Abstract Concepts"),
    _k("挟", "pinch/between", "キョウ", None, "Actions & Abstract Concepts"),
    _k("捨", "discard/throw away", "シャ", None, "Actions & Abstract Concepts"),
    _k("裏", "back/reverse/inside", "リ", None, "Actions & Abstract Concepts"),
    _k("詰", "packed/close", "キツ", None, "Actions & Abstract Concepts"),
    _k("片", "one-sided/leaf/sheet", "ヘン", None, "Actions & Abstract Concepts"),
    _k("肯", "agreement/consent", "コウ", None, "Actions & Abstract Concepts"),
    _k("依", "reliant/depend on", "イ", None, "Actions & Abstract Concepts"),
    _k("符", "token/sign/mark", "フ", None, "Actions & Abstract Concepts"),
    _k("伸", "expand/stretch", "シン", None, "Actions & Abstract Concepts"),
    _k("掘", "dig/delve/excavate", "クツ", None, "Actions & Abstract Concepts"),
    _k("捜", "search/look for", "ソウ", None, "Actions & Abstract Concepts"),
    _k("採", "pick/take/fetch", "サイ", None, "Actions & Abstract Concepts"),
    _k("練", "practice/train/drill", "レン", None, "Actions & Abstract Concepts"),
    _k("毒", "poison/virus/venom", "ドク", None, "Actions & Abstract Concepts"),
    _k("並", "row/rank/rival/equal", "ヘイ", None, "Actions & Abstract Concepts"),
    _k("双", "pair/set/comparison", "ソウ", None, "Actions & Abstract Concepts"),
    _k("翌", "the following/next", "ヨク", None, "Actions & Abstract Concepts"),
    _k("久", "long time", "キュウ", None, "Actions & Abstract Concepts"),
    _k("幼", "infancy/childhood", "ヨウ", None, "Actions & Abstract Concepts"),
    _k("延", "prolong/stretching", "エン", None, "Actions & Abstract Concepts"),
    _k("泊", "overnight/put up", "ハク", None, "Actions & Abstract Concepts"),
    _k("航", "navigate/sail/cruise", "コウ", None, "Actions & Abstract Concepts"),
    _k("卒", "graduate/soldier/die", None, "そつ", None),
    _k("臓", "entrails/viscera", "ゾウ", None, None),
    _k("兆", "portent/trillion", "チョウ", None, None),
)
