"""JLPT N1 kanji seed data.

Extracted from the Mensura Media reference chart
``japanese/jp_kanji/reference_chart_kanji_n1.pdf`` in the companion
`language-learning <https://github.com/MensuraMedia/language-learning>`_ repository,
which is the authority for this project's character data.

On'yomi are written in katakana and kun'yomi in hiragana, matching the
convention fixed by the content model. The charts give readings in wapuro
romaji; conversion to kana is mechanical and every reading was verified by
converting back and comparing. Where a chart states only one reading it does
not say which kind it is, so the field is chosen from a lexicon built from the
664 explicit on/kun pairs across all five levels — a held-out test of that
rule against the N1 pairs scored 94.6%. **Kanji cards are graded on the
meaning**, so a mislabelled reading affects the reference rows on the card
back and nothing that is scored.

Kun'yomi are the chart's whole-word readings; okurigana are not bracketed as
they are in :mod:`.kanji_n5`. Stroke counts are not in the charts and are left
unset.
"""

from __future__ import annotations

from ..models import CharacterSeed

__all__ = ["KANJI_N1"]


def _k(
    glyph: str,
    meaning: str,
    onyomi: str | None,
    kunyomi: str | None,
    category: str | None,
) -> CharacterSeed:
    """Build a N1 kanji seed with the shared script/level fields filled in."""
    return CharacterSeed(
        glyph=glyph,
        script="kanji",
        meaning=meaning,
        onyomi=onyomi,
        kunyomi=kunyomi,
        jlpt_level="N1",
        category=category,
    )


#: 337 characters, in chart order.
KANJI_N1: tuple[CharacterSeed, ...] = (
    _k("憧", "yearn/admire", "ドウ", "あこがれる", "Emotions & Character"),
    _k("哀", "grief/sorrow", "アイ", "あわれ", "Emotions & Character"),
    _k("惜", "regret/spare", "セキ", "おしむ", "Emotions & Character"),
    _k("慰", "console/comfort", "イ", "なぐさめる", "Emotions & Character"),
    _k("慨", "lament", "ガイ", None, "Emotions & Character"),
    _k("憶", "remember", "オク", None, "Emotions & Character"),
    _k("悼", "mourn", "トウ", "いたむ", "Emotions & Character"),
    _k("憂", "worry/grief", "ユウ", "うれえる", "Emotions & Character"),
    _k("憐", "pity", "レン", None, "Emotions & Character"),
    _k("懐", "nostalgia", "カイ", "なつかしい", "Emotions & Character"),
    _k("怖", "dread", "フ", "こわい", "Emotions & Character"),
    _k("愁", "worry", "シュウ", "うれえる", "Emotions & Character"),
    _k("愉", "pleasant", "ユ", None, "Emotions & Character"),
    _k("懇", "sympathy", "ドウ", None, "Emotions & Character"),
    _k("恨", "grudge", "コン", "うらむ", "Emotions & Character"),
    _k("悔", "regret", "カイ", "くいる", "Emotions & Character"),
    _k("瘤", "tumor", "リュウ", None, "Body & Medicine"),
    _k("痘", "smallpox", "トウ", None, "Body & Medicine"),
    _k("痕", "scar/mark", "コン", None, "Body & Medicine"),
    _k("痩", "thin/emaciate", "ソウ", "やせる", "Body & Medicine"),
    _k("疾", "disease", "シツ", None, "Body & Medicine"),
    _k("痴", "infatuated", "チ", None, "Body & Medicine"),
    _k("肢", "limb", "シ", None, "Body & Medicine"),
    _k("脱", "undress", "ダツ", "ぬぐ", "Body & Medicine"),
    _k("澄", "clear/■", "チョウ", "すむ", "Nature & Weather"),
    _k("濡", "moisten", "ジュウ", "うるおう", "Nature & Weather"),
    _k("涌", "gush/spring", "ヨウ", "わく", "Nature & Weather"),
    _k("沢", "swamp", "タク", "さわ", "Nature & Weather"),
    _k("峨", "steep/severe", "ガ", "けわしい", "Nature & Weather"),
    _k("焦", "scorch", "ショウ", "こげる", "Nature & Weather"),
    _k("虹", "rainbow", "コウ", "にじ", "Nature & Weather"),
    _k("炎", "flame/■", "エン", None, "Nature & Weather"),
    _k("浄", "pure/clean", "ジョウ", None, "Nature & Weather"),
    _k("浮", "float", "フ", "うく", "Nature & Weather"),
    _k("淀", "pool", "テン", "よど", "Nature & Weather"),
    _k("溝", "ditch", "コウ", "みぞ", "Nature & Weather"),
    _k("滞", "stagnate", "タイ", "とどこる", "Nature & Weather"),
    _k("蘭", "orchid", "ラン", None, "Plants & Animals"),
    _k("檀", "sandalwood", "ダン", None, "Plants & Animals"),
    _k("棘", "thorn", "コウ", "とげ", "Plants & Animals"),
    _k("芽", "bud/sprout", "ガ", "め", "Plants & Animals"),
    _k("蓮", "lotus", "レン", "はす", "Plants & Animals"),
    _k("葡", "grape", "ブ", "ぶど", "Plants & Animals"),
    _k("萄", "grape vine", "トウ", None, "Plants & Animals"),
    _k("楠", "camphor", "ナン", "くす", "Plants & Animals"),
    _k("柿", "persimmon", "シ", "かき", "Plants & Animals"),
    _k("檜", "cypress", None, "ひのき", "Plants & Animals"),
    _k("笹", "bamboo grass", None, "ささ", "Plants & Animals"),
    _k("蜂", "bee", "ホウ", "はち", "Plants & Animals"),
    _k("螺", "■/snail", "ラ", "にし", "Plants & Animals"),
    _k("蝶", "butterfly", "チョウ", None, "Plants & Animals"),
    _k("蛇", "snake", "ジャ", "へび", "Plants & Animals"),
    _k("鹿", "deer", "ロク", "しか", "Plants & Animals"),
    _k("狼", "wolf", "ロウ", "おおかみ", "Plants & Animals"),
    _k("羊", "sheep", "ヨウ", "ひつじ", "Plants & Animals"),
    _k("蛍", "firefly", "ケイ", "ほたる", "Plants & Animals"),
    _k("蝗", "locust", "コウ", None, "Plants & Animals"),
    _k("麗", "lovely", "レイ", "うるわしい", "Colors & Aesthetics"),
    _k("剣", "sword", "ケン", "つるぎ", "Tools & Weapons"),
    _k("鎌", "sickle", "レン", "かま", "Tools & Weapons"),
    _k("笛", "flute", "テキ", "ふえ", "Tools & Weapons"),
    _k("拘", "arrest/adhere", "コウ", "かかわる", "Abstract & Philosophical"),
    _k("促", "urge/promote", "ソク", "うながす", "Actions & Movement"),
    _k("叙", "describe", "ジョ", "のぶ", "Actions & Movement"),
    _k("吹", "blow", "スイ", "ふく", "Actions & Movement"),
    _k("掌", "palm of hand", "ショウ", "てのひら", "Actions & Movement"),
    _k("推", "push/infer", "スイ", "おす", "Actions & Movement"),
    _k("揮", "brandish/wield", "キ", "ふるう", "Actions & Movement"),
    _k("搭", "board/load", "トウ", "のせる", "Actions & Movement"),
    _k("摂", "take in/■", "セツ", "とる", "Actions & Movement"),
    _k("撲", "strike", "ボク", "うつ", "Actions & Movement"),
    _k("捧", "lift up/offer", "ホウ", "ささげる", "Actions & Movement"),
    _k("擦", "rub", "サツ", "する", "Actions & Movement"),
    _k("斜", "diagonal", "シャ", "ななめ", "Actions & Movement"),
    _k("施", "carry out", "セ", "し", "Actions & Movement"),
    _k("暮", "dusk/■", "ボ", "くれる", "Actions & Movement"),
    _k("曝", "expose", "バク", "さらす", "Actions & Movement"),
    _k("漂", "drift/float", "ヒョウ", "ただよう", "Actions & Movement"),
    _k("襲", "attack/raid", "シュウ", "おそう", "Actions & Movement"),
    _k("踏", "step/trample", "トウ", "ふむ", "Actions & Movement"),
    _k("躍", "leap/active", "ヤク", None, "Actions & Movement"),
    _k("迎", "welcome", "ゲイ", "むかえる", "Actions & Movement"),
    _k("遣", "dispatch", "ケン", "つかわす", "Actions & Movement"),
    _k("遷", "transition", "セン", "うつる", "Actions & Movement"),
    _k("還", "return/■", "カン", "かえる", "Actions & Movement"),
    _k("酔", "drunk", "スイ", "よう", "Actions & Movement"),
    _k("騒", "noisy", "ソウ", "さわぐ", "Actions & Movement"),
    _k("伴", "accompany", "ハン", "ともなう", "Society & Culture"),
    _k("妥", "proper/compromise", "ダ", None, "Quality & State"),
    _k("僅", "merely/only", "キン", "わずか", "Quality & State"),
    _k("冗", "a redundant", "ジョウ", None, "Quality & State"),
    _k("厳", "strict/severe", "ゲン", "ごん", "Quality & State"),
    _k("玄", "mysterious", "ゲン", None, "Quality & State"),
    _k("甚", "extreme", "ジン", "はなはだ", "Quality & State"),
    _k("偉", "great/admirable", "イ", "えらい", "Quality & State"),
    _k("健", "healthy", "ケン", "すこやか", "Quality & State"),
    _k("偽", "fake/forgery", "ギ", "にせ", "Quality & State"),
    _k("傍", "beside", "ボウ", "かたわら", "Quality & State"),
    _k("卑", "lowly", "ヒ", "いやしい", "Quality & State"),
    _k("博", "extensive", "ハク", None, "Quality & State"),
    _k("壮", "robust", "ソウ", None, "Quality & State"),
    _k("幽", "faint/dim", "ユウ", None, "Quality & State"),
    _k("凡", "commonplace", "ボン", "はん", "Quality & State"),
    _k("精", "■/essence", "セイ", "しょう", "Quality & State"),
    _k("傅", "tutor", "フ", None, "Society & Culture"),
    _k("仰", "look up", "ギョウ", "あおぐ", "Society & Culture"),
    _k("企", "plan/undertake", "キ", "くわだてる", "Society & Culture"),
    _k("俊", "genius/talent", "シュン", None, "Society & Culture"),
    _k("儀", "ceremony/model", "ギ", None, "Society & Culture"),
    _k("譲", "yield/defer", "ジョウ", "ゆずる", "Communication & Thought"),
    _k("詐", "fraud/deceive", "サ", None, "Communication & Thought"),
    _k("謡", "ballad/rumor", "ヨウ", None, "Communication & Thought"),
    _k("誉", "honor/praise", "ヨ", "ほまれ", "Communication & Thought"),
    _k("謙", "humble/modest", "ケン", None, "Communication & Thought"),
    _k("戒", "admonish", "カイ", None, "Communication & Thought"),
    _k("咽", "swallow", "イン", "のめ", "Communication & Thought"),
    _k("唱", "chant", "ショウ", "となえ", "Communication & Thought"),
    _k("忌", "avoid/taboo", "キ", "いむ", "Communication & Thought"),
    _k("忠", "loyalty", "チュウ", None, "Communication & Thought"),
    _k("悟", "enlighten", "ゴ", "さとる", "Communication & Thought"),
    _k("窪", "hollow", "ワ", "くぼ", "Buildings & Geography"),
    _k("囚", "prisoner", "シュウ", None, "Buildings & Geography"),
    _k("坑", "pit", "コウ", None, "Buildings & Geography"),
    _k("塵", "dust", "ジン", "ほこり", "Buildings & Geography"),
    _k("壇", "platform", "ダン", None, "Buildings & Geography"),
    _k("屈", "yield/bend", "クツ", None, "Buildings & Geography"),
    _k("展", "exhibit/display", "テン", None, "Buildings & Geography"),
    _k("庵", "hermitage", "アン", "いおり", "Buildings & Geography"),
    _k("廊", "corridor", "ロウ", None, "Buildings & Geography"),
    _k("柏", "oak", "ハク", "かしわ", "Buildings & Geography"),
    _k("欄", "column", "ラン", None, "Buildings & Geography"),
    _k("圏", "sphere", "ケン", None, "Buildings & Geography"),
    _k("廷", "court", "テイ", None, "Buildings & Geography"),
    _k("扉", "door/■", "ヒ", None, "Buildings & Geography"),
    _k("幣", "coin/currency", "ヘイ", None, "Food & Materials"),
    _k("財", "wealth", "ザイ", "さい", "Food & Materials"),
    _k("瓦", "roof tile", "ガ", "かわら", "Food & Materials"),
    _k("珠", "pearl", "シュ", "たま", "Food & Materials"),
    _k("輝", "shine/radiate", "キ", "かがやく", "Colors & Aesthetics"),
    _k("彩", "coloring", "サイ", "いろどり", "Colors & Aesthetics"),
    _k("彫", "carve/sculpt", "チョウ", "ほる", "Colors & Aesthetics"),
    _k("縞", "stripe", "ホウ", "しま", "Colors & Aesthetics"),
    _k("錦", "brocade", "キン", "にしき", "Colors & Aesthetics"),
    _k("廃", "abolish", "ハイ", "すたれる", "Abstract & Philosophical"),
    _k("辱", "humiliate", "ジョク", None, "Abstract & Philosophical"),
    _k("妄", "reckless", "ボウ", "みだり", "Abstract & Philosophical"),
    _k("迪", "enlighten", "テキ", None, "Abstract & Philosophical"),
    _k("倫", "ethics", "リン", None, "Abstract & Philosophical"),
    _k("既", "already", "キ", "すで", "Abstract & Philosophical"),
    _k("称", "name/■", "ショウ", None, "Abstract & Philosophical"),
    _k("稲", "rice plant", "トウ", "いね", "Abstract & Philosophical"),
    _k("稿", "draft/■", "コウ", None, "Abstract & Philosophical"),
    _k("穂", "ear of grain", "スイ", "ほ", "Abstract & Philosophical"),
    _k("策", "plan/scheme", "サク", None, "Abstract & Philosophical"),
    _k("篠", "bamboo", "ショウ", "しの", "Abstract & Philosophical"),
    _k("簾", "bamboo blind", "レン", "すだれ", "Abstract & Philosophical"),
    _k("網", "net", "モウ", "あみ", "Abstract & Philosophical"),
    _k("耐", "endure", "タイ", "たえる", "Abstract & Philosophical"),
    _k("耗", "consume/wear", "モウ", "へる", "Abstract & Philosophical"),
    _k("聖", "holy/saint", "セイ", "ひじり", "Abstract & Philosophical"),
    _k("聴", "listen", "チョウ", "きく", "Abstract & Philosophical"),
    _k("暦", "calendar", "レキ", None, "Abstract & Philosophical"),
    _k("叡", "recite/chant", "エイ", None, None),
    _k("愛", "love", "アイ", None, None),
    _k("曖", "vague/ambiguous", "アイ", "あいまい", None),
    _k("嬉", "frolic", "キ", "たわむれる", None),
    _k("妖", "bewitching", "ヨウ", "あやしい", None),
    _k("謊", "conspiracy", "ボウ", None, None),
    _k("賂", "bribe", "ロク", None, None),
    _k("勅", "imperial order", "チョク", None, None),
    _k("診", "diagnose", "シン", None, None),
    _k("詎", "cross-examine", "キツ", None, None),
    _k("詣", "levy/collect", "チョウ", None, None),
    _k("僕", "servant/I", "ボク", None, None),
    _k("幾", "how many", "キ", "いく", None),
    _k("罠", "dismiss/quit", "ヒ", None, None),
    _k("羨", "envy", "セン", "うらやむ", None),
    _k("訌", "satirize", "フウ", None, None),
    _k("渚", "estuary", "ショ", None, None),
    _k("淫", "lewd", "イン", "みだら", None),
    _k("沌", "stagnant", "ドン", None, None),
    _k("畸", "warp/distort", "キ", "いびつ", None),
    _k("柴", "firewood", "サイ", "しば", None),
    _k("茉", "jasmine", "マツ", "すえ", None),
    _k("梁", "beam/ridge", "リョウ", None, None),
    _k("欅", "zelkova", None, "けやき", None),
    _k("鮫", "shark", "コウ", "さめ", None),
    _k("鰯", "blowfish", None, "ふぐ", None),
    _k("麓", "foot of mountain", "ロク", None, None),
    _k("惣", "concept/idea", "ソウ", None, None),
    _k("厄", "misfortune", "ヤク", None, None),
    _k("晦", "world/■", "カイ", None, None),
    _k("撃", "strike/attack", "ゲキ", "うつ", None),
    _k("掴", "rub/print", "サツ", "する", None),
    _k("斑", "spot/speckle", "ハン", None, None),
    _k("喉", "throat", "コウ", "のど", None),
    _k("哉", "alas", "サイ", "かな", None),
    _k("慎", "discreet", "シン", None, None),
    _k("冷", "cold", "レイ", "つめたい", None),
    _k("勃", "force", "ボツ", None, None),
    _k("基", "base/foundation", "キ", "もと", None),
    _k("壊", "destroy", "カイ", "こわれる", None),
    _k("孔", "Confucius/hole", "コウ", None, None),
    _k("孝", "filial piety", "コウ", None, None),
    _k("寧", "rather/peaceful", "ネイ", None, None),
    _k("寮", "dormitory", "リョウ", None, None),
    _k("履", "footwear/history", "リ", "はく", None),
    _k("崇", "worship/adore", "スウ", "あがめる", None),
    _k("徴", "symptom/sign", "チョウ", None, None),
    _k("慣", "accustom", "カン", "なれる", None),
    _k("折", "fold/break", "セツ", "おる", None),
    _k("捻", "twist", "ネン", "ひねる", None),
    _k("揃", "arrange/gather", "ソウ", "そろう", None),
    _k("暖", "warm", "ダン", "あたたかい", None),
    _k("曲", "bend/curve", "キョク", "まがる", None),
    _k("最", "most", "サイ", "もっとも", None),
    _k("枠", "frame", None, "わく", None),
    _k("柳", "willow", "リュウ", "やなぎ", None),
    _k("桜", "cherry tree", "オウ", "さくら", None),
    _k("欠", "lack/yawn", "ケツ", "かける", None),
    _k("殖", "propagate", "ショク", "ふえる", None),
    _k("殺", "kill", "サツ", "ころす", None),
    _k("汰", "peace/Thai", "タイ", None, None),
    _k("浸", "immerse/soak", "シン", "ひたす", None),
    _k("潘", "accompany", "ハン", "ともなう", None),
    _k("瓷", "porcelain", "ジ", None, None),
    _k("畔", "tray/board", "バン", None, None),
    _k("監", "oversee", "カン", None, None),
    _k("眉", "eyebrow", "ビ", "まゆ", None),
    _k("瞬", "blink/instant", "シュン", "またたく", None),
    _k("禅", "Zen", "ゼン", None, None),
    _k("級", "class/grade", "キュウ", None, None),
    _k("羞", "shame", "シュウ", None, None),
    _k("耶", "Jesus/■", "ヤ", None, None),
    _k("脹", "swell/expand", "チョウ", "ふくれる", None),
    _k("舗", "shop/store", "ホ", None, None),
    _k("艇", "boat/■", "テイ", None, None),
    _k("苗", "seedling", "ビョウ", "なえ", None),
    _k("茂", "overgrow", "モウ", "しげる", None),
    _k("萩", "bush clover", None, "はぎ", None),
    _k("薩", "Satsuma", "サツ", None, None),
    _k("蘇", "revive", "ソ", "よみがえる", None),
    _k("衆", "masses/public", "シュウ", None, None),
    _k("衷", "■ heart", "スイ", "おとずれる", None),
    _k("裁", "cut/judge", "サイ", "たつ", None),
    _k("豌", "penniless", None, "びん", None),
    _k("貌", "appearance", "ボウ", None, None),
    _k("跌", "fall/stumble", "テツ", None, None),
    _k("郎", "young man", "ロウ", None, None),
    _k("醬", "soy sauce", "ショウ", None, None),
    _k("鎮", "calm/suppress", "チン", "しずめる", None),
    _k("鑑", "appraise", "カン", None, None),
    _k("閣", "tower/cabinet", "カク", None, None),
    _k("陣", "camp/■", "ジン", None, None),
    _k("雄", "male/hero", "ユウ", "おす", None),
    _k("難", "difficult", "ナン", "むずかしい", None),
    _k("霊", "spirit/soul", "レイ", "りょう", None),
    _k("韓", "Korea/■", "カン", None, None),
    _k("項", "clause/■", "コウ", None, None),
    _k("顧", "look back", "コ", "かえりみる", None),
    _k("餌", "bait/feed", "ジ", "えさ", None),
    _k("餓", "starve", "ガ", "うえる", None),
    _k("鬼", "demon/ghost", "キ", "おに", None),
    _k("魂", "soul/spirit", "コン", "たましい", None),
    _k("魅", "fascinate", "ミ", None, None),
    _k("両", "both", "リョウ", None, None),
    _k("丹", "red/sincerity", "タン", None, None),
    _k("亡", "perish", "ボウ", "ない", None),
    _k("俑", "wait", "コウ", None, None),
    _k("催", "■/sponsor", "サイ", "もよおす", None),
    _k("兎", "rabbit", "ト", "うさぎ", None),
    _k("劫", "robbery", "ゴウ", None, None),
    _k("勾", "hook", "コウ", None, None),
    _k("匠", "artisan", "ショウ", None, None),
    _k("卯", "sign/rabbit", "ボウ", None, None),
    _k("卸", "wholesale", None, "おろし", None),
    _k("唐", "Tang/China", "トウ", "から", None),
    _k("啓", "open/■", "ケイ", "ひらく", None),
    _k("喘", "asthma/pant", "ゼン", "あえぐ", None),
    _k("嘉", "praise/■", "カ", None, None),
    _k("噂", "lie/falsehood", None, "うそ", None),
    _k("執", "tenacious", "シュウ", None, None),
    _k("堆", "pile up", "タイ", "つむ", None),
    _k("堕", "degenerate", "ダ", None, None),
    _k("増", "increase", "ゾウ", "ます", None),
    _k("契", "pledge", "ケイ", "ちぎる", None),
    _k("娯", "entertain", "ゴ", None, None),
    _k("宛", "banquet", "エン", None, None),
    _k("尾", "tail", "ビ", "お", None),
    _k("局", "bureau", "キョク", None, None),
    _k("幹", "trunk/main", "カン", "みき", None),
    _k("弔", "condole", "チョウ", "とむらう", None),
    _k("徐", "slowly", "ジョ", None, None),
    _k("御", "honorable", "ゴ/ギョ", "おん", None),
    _k("怕", "fear", "フ", "こわい", None),
    _k("斉", "stall equal", "セイ", None, None),
    _k("昌", "prosperity", "ショウ", None, None),
    _k("杉", "cedar", "サン", "すぎ", None),
    _k("椎", "mallet", "ツイ", None, None),
    _k("殊", "special", "シュ", "こと", None),
    _k("漸", "gradually", "ゼン", None, None),
    _k("句", "phrase/■", "ク", None, None),
    _k("唆", "instigate", "サ", "そそのかす", None),
    _k("冒", "risk/■", "ボウ", "おかす", None),
    _k("謀", "conspire", "ボウ", None, None),
    _k("又", "again/■", None, "また", None),
    _k("吉", "good luck", "キチ", None, None),
    _k("吾", "I/oneself", "ゴ", "われ", None),
    _k("姿", "figure/form", "シ", "すがた", None),
    _k("岐", "branch/■", "キ", None, None),
    _k("峰", "peak/summit", "ホウ", "みね", None),
    _k("帳", "notebook", "チョウ", None, None),
    _k("弦", "bowstring", "ゲン", "つる", None),
    _k("彦", "lad/prince", None, "ひこ", None),
    _k("径", "diameter", "ケイ", None, None),
    _k("徹", "thorough", "テツ", None, None),
    _k("把", "grasp", "ハ", "わ", None),
    _k("拐", "kidnap", "カイ", None, None),
    _k("拠", "basis", "キョ", "よる", None),
    _k("援", "aid/■", "エン", None, None),
    _k("朕", "first day", "サク", None, None),
    _k("桐", "paulownia", "トウ", "きり", None),
    _k("椿", "camellia", "チン", "つばき", None),
    _k("瀏", "browse", "ラン", None, None),
    _k("熊", "bear animal", "ユウ", "くま", None),
    _k("燈", "lamp", "トウ", None, None),
    _k("猛", "fierce", "モウ", None, None),
    _k("矛", "spear", "モウ", "ほこ", None),
    _k("穴", "hole", "ケツ", "あな", None),
    _k("絞", "squeeze", "コウ", "しぼる", None),
    _k("聘", "invite/hire", "ヘイ", None, None),
    _k("艦", "warship", "カン", None, None),
    _k("苑", "garden", "エン", None, None),
    _k("莉", "jasmine", "リ", None, None),
    _k("蓄", "store", "チク", None, None),
    _k("蘆", "reed", "ロ", None, None),
    _k("請", "request", "シン", None, None),
)
