"""JLPT N3 kanji seed data.

Extracted from the Mensura Media reference chart
``japanese/jp_kanji/reference_chart_kanji_n3.pdf`` in the companion
`language-learning <https://github.com/MensuraMedia/language-learning>`_ repository,
which is the authority for this project's character data.

On'yomi are written in katakana and kun'yomi in hiragana, matching the
convention fixed by the content model. The charts give readings in wapuro
romaji; conversion to kana is mechanical and every reading was verified by
converting back and comparing. Where a chart states only one reading it does
not say which kind it is, so the field is chosen from a lexicon built from the
664 explicit on/kun pairs across all five levels — a held-out test of that
rule against the N1 pairs scored 94.6%. **Kanji cards are graded on the
meaning**, so a mislabelled reading affects the reference rows on the card
back and nothing that is scored.

Kun'yomi are the chart's whole-word readings; okurigana are not bracketed as
they are in :mod:`.kanji_n5`. Stroke counts are not in the charts and are left
unset.
"""

from __future__ import annotations

from ..models import CharacterSeed

__all__ = ["KANJI_N3"]


def _k(
    glyph: str,
    meaning: str,
    onyomi: str | None,
    kunyomi: str | None,
    category: str | None,
) -> CharacterSeed:
    """Build a N3 kanji seed with the shared script/level fields filled in."""
    return CharacterSeed(
        glyph=glyph,
        script="kanji",
        meaning=meaning,
        onyomi=onyomi,
        kunyomi=kunyomi,
        jlpt_level="N3",
        category=category,
    )


#: 396 characters, in chart order.
KANJI_N3: tuple[CharacterSeed, ...] = (
    _k("政", "politics", "セイ", "まつりごと", "Government & Law"),
    _k("治", "govern/cure", "チ", "おさめる", "Government & Law"),
    _k("法", "law/method", "ホウ", None, "Government & Law"),
    _k("経", "pass through", "ケイ", "へる", "Government & Law"),
    _k("済", "settle", "サイ", "すむ", "Government & Law"),
    _k("税", "tax", "ゼイ", None, "Government & Law"),
    _k("選", "choose", "セン", "えらぶ", "Government & Law"),
    _k("挙", "raise/elect", "キョ", "あげる", "Government & Law"),
    _k("権", "authority", "ケン", None, "Government & Law"),
    _k("議", "deliberation", "ギ", None, "Government & Law"),
    _k("民", "people", "ミン", "たみ", "Government & Law"),
    _k("制", "system", "セイ", None, "Government & Law"),
    _k("律", "law/rhythm", "リツ", None, "Government & Law"),
    _k("禁", "prohibit", "キン", None, "Government & Law"),
    _k("報", "report", "ホウ", None, "Communication & Reports"),
    _k("告", "announce", "コク", "つげる", "Communication & Reports"),
    _k("示", "show", "ジ", "しめす", "Communication & Reports"),
    _k("表", "surface", "ヒョウ", "おもて", "Communication & Reports"),
    _k("現", "appear", "ゲン", "あらわれる", "Communication & Reports"),
    _k("実", "truth/fruit", "ジツ", "み", "Communication & Reports"),
    _k("認", "recognize", "ニン", "みとめる", "Communication & Reports"),
    _k("調", "investigate", "チョウ", "しらべる", "Communication & Reports"),
    _k("論", "theory", "ロン", None, "Communication & Reports"),
    _k("証", "proof", "ショウ", None, "Communication & Reports"),
    _k("評", "evaluate", "ヒョウ", None, "Communication & Reports"),
    _k("詳", "detailed", "ショウ", "くわしい", "Communication & Reports"),
    _k("述", "state", "ジュツ", "のべる", "Communication & Reports"),
    _k("訳", "translate", "ヤク", "わけ", "Communication & Reports"),
    _k("官", "government", "カン", None, "People & Roles"),
    _k("客", "guest/customer", "キャク", None, "People & Roles"),
    _k("身", "body/oneself", "シン", "み", "People & Roles"),
    _k("相", "mutual", "ソウ", "あい", "People & Roles"),
    _k("役", "role/service", "ヤク", "えき", "People & Roles"),
    _k("指", "finger/point", "シ", "ゆび", "People & Roles"),
    _k("師", "teacher/master", "シ", None, "People & Roles"),
    _k("配", "distribute", "ハイ", "くばる", "People & Roles"),
    _k("件", "matter/case", "ケン", None, "People & Roles"),
    _k("老", "old age", "ロウ", "おいる", "People & Roles"),
    _k("島", "island", "トウ", "しま", "Nature & Seasons"),
    _k("陸", "land", "リク", None, "Nature & Seasons"),
    _k("谷", "valley", "コク", "たに", "Nature & Seasons"),
    _k("港", "harbor", "コウ", "みなと", "Nature & Seasons"),
    _k("湖", "lake", "コ", "みずうみ", "Nature & Seasons"),
    _k("温", "warm", "オン", "あたたかい", "Nature & Seasons"),
    _k("熱", "heat/fever", "ネツ", "あつい", "Nature & Seasons"),
    _k("寒", "cold", "カン", "さむい", "Nature & Seasons"),
    _k("涼", "cool", "リョウ", "すずしい", "Nature & Seasons"),
    _k("氷", "ice", "ヒョウ", "こおり", "Nature & Seasons"),
    _k("星", "star", "セイ", "ほし", "Nature & Seasons"),
    _k("陽", "sun/positive", "ヨウ", "ひ", "Nature & Seasons"),
    _k("葉", "leaf", "ヨウ", "は", "Nature & Seasons"),
    _k("草", "grass", "ソウ", "くさ", "Nature & Seasons"),
    _k("猫", "cat", "ビョウ", "ねこ", "Animals & Nature"),
    _k("虫", "insect", "チュウ", "むし", "Animals & Nature"),
    _k("農", "agriculture", "ノウ", None, "Animals & Nature"),
    _k("種", "seed/kind", "シュ", "たね", "Animals & Nature"),
    _k("根", "root", "コン", "ね", "Animals & Nature"),
    _k("育", "raise/grow", "イク", "そだてる", "Animals & Nature"),
    _k("荷", "luggage/load", "カ", "に", "Animals & Nature"),
    _k("畑", "farm field", None, "はたけ", "Animals & Nature"),
    _k("血", "blood", "ケツ", "ち", "Body & Health"),
    _k("骨", "bone", "コツ", None, "Body & Health"),
    _k("皮", "skin/leather", "ヒ", "かわ", "Body & Health"),
    _k("毛", "hair/fur", "モウ", "け", "Body & Health"),
    _k("息", "breath", "ソク", "いき", "Body & Health"),
    _k("肌", "skin", "キ", "はだ", "Body & Health"),
    _k("胸", "chest", "キョウ", "むね", "Body & Health"),
    _k("腕", "arm", "ワン", "うで", "Body & Health"),
    _k("腰", "waist/hip", "ヨウ", "こし", "Body & Health"),
    _k("背", "back/height", "ハイ", "せ", "Body & Health"),
    _k("腸", "intestine", "チョウ", None, "Body & Health"),
    _k("泣", "cry/weep", "キュウ", "なく", "Emotions & Feelings"),
    _k("笑", "laugh/smile", "ショウ", "わらう", "Emotions & Feelings"),
    _k("怒", "anger", "ド", "おこる", "Emotions & Feelings"),
    _k("悲", "sad/grief", "ヒ", "かなしい", "Emotions & Feelings"),
    _k("喜", "joy/delight", "キ", "よろこぶ", "Emotions & Feelings"),
    _k("感", "feel/emotion", "カン", None, "Emotions & Feelings"),
    _k("情", "feeling", "ジョウ", "なさけ", "Emotions & Feelings"),
    _k("恋", "love/romance", "レン", "こい", "Emotions & Feelings"),
    _k("恐", "fear", "キョウ", "おそれる", "Emotions & Feelings"),
    _k("患", "afflict", "カン", "わずらう", "Emotions & Feelings"),
    _k("志", "will/ambition", "シ", None, "Emotions & Feelings"),
    _k("橋", "bridge", "キョウ", "はし", "Buildings & Places"),
    _k("階", "floor/story", "カイ", None, "Buildings & Places"),
    _k("窓", "window", "ソウ", "まど", "Buildings & Places"),
    _k("壁", "wall", "ヘキ", "かべ", "Buildings & Places"),
    _k("庭", "garden", "テイ", "にわ", "Buildings & Places"),
    _k("床", "floor/bed", "ショウ", "ゆか", "Buildings & Places"),
    _k("席", "seat", "セキ", None, "Buildings & Places"),
    _k("寺", "down temple", "ジ", "てら", "Buildings & Places"),
    _k("宿", "lodge/inn", "シュク", "やど", "Buildings & Places"),
    _k("建", "build", "ケン", "たてる", "Buildings & Places"),
    _k("向", "face/turn", "コウ", "むく", "Direction & Position"),
    _k("側", "side", "ソク", "がわ", "Direction & Position"),
    _k("奥", "interior", "オウ", "おく", "Direction & Position"),
    _k("底", "bottom", "テイ", "そこ", "Direction & Position"),
    _k("辺", "vicinity", "ヘン", "あたり", "Direction & Position"),
    _k("周", "around", "シュウ", None, "Direction & Position"),
    _k("囲", "surround", "イ", "かこむ", "Direction & Position"),
    _k("央", "center", "オウ", None, "Direction & Position"),
    _k("端", "edge/end", "タン", "はし", "Direction & Position"),
    _k("内", "inside", "ナイ", "うち", "Direction & Position"),
    _k("境", "boundary", "キョウ", "さかい", "Direction & Position"),
    _k("進", "advance", "シン", "すすむ", "Actions & Movement"),
    _k("退", "retreat", "タイ", "しりぞく", "Actions & Movement"),
    _k("逃", "escape", "トウ", "にげる", "Actions & Movement"),
    _k("受", "receive", "ジュ", "うける", "Actions & Movement"),
    _k("取", "take", "シュ", "とる", "Actions & Movement"),
    _k("戻", "return", "レイ", "もどす", "Actions & Movement"),
    _k("移", "move/shift", "イ", "うつる", "Actions & Movement"),
    _k("落", "fall/drop", "ラク", "おちる", "Actions & Movement"),
    _k("投", "throw", "トウ", "なげる", "Actions & Movement"),
    _k("拾", "pick up", "シュウ", "ひろう", "Actions & Movement"),
    _k("攻", "attack", "コウ", "せめる", "Actions & Movement"),
    _k("労", "labor", "ロウ", None, "Work & Economy"),
    _k("勤", "work/serve", "キン", "つとめる", "Work & Economy"),
    _k("務", "duty", "ム", "つとめる", "Work & Economy"),
    _k("職", "employment", "ショク", None, "Work & Economy"),
    _k("給", "salary", "キュウ", None, "Work & Economy"),
    _k("費", "expense", "ヒ", "ついやす", "Work & Economy"),
    _k("資", "resources", "シ", None, "Work & Economy"),
    _k("益", "profit/benefit", "エキ", None, "Work & Economy"),
    _k("損", "loss/damage", "ソン", None, "Work & Economy"),
    _k("商", "commerce", "ショウ", "あきんど", "Work & Economy"),
    _k("貿", "trade", "ボウ", None, "Work & Economy"),
    _k("輸", "transport", "ユ", None, "Work & Economy"),
    _k("収", "collect/income", "シュウ", "おさめる", "Work & Economy"),
    _k("支", "support", "シ", "ささえる", "Work & Economy"),
    _k("厚", "thick", "コウ", "あつい", "Size & Quality"),
    _k("深", "deep", "シン", "ふかい", "Size & Quality"),
    _k("浅", "shallow", "セン", "あさい", "Size & Quality"),
    _k("清", "clean/pure", "セイ", "きよい", "Size & Quality"),
    _k("汚", "dirty", "オ", "よごす", "Size & Quality"),
    _k("乾", "dry", "カン", None, "Size & Quality"),
    _k("湿", "damp", "シツ", "しめる", "Size & Quality"),
    _k("豊", "abundant", "ホウ", "ゆたか", "Size & Quality"),
    _k("貧", "poor", "ヒン", "まずしい", "Size & Quality"),
    _k("富", "wealth", "フ", "とみ", "Size & Quality"),
    _k("苦", "bitter/suffer", "ク", "にがい", "Size & Quality"),
    _k("痛", "pain", "ツウ", "いたむ", "Size & Quality"),
    _k("危", "danger", "キ", "あぶない", "Size & Quality"),
    _k("短", "short", "タン", "みじかい", "Size & Quality"),
    _k("硬", "hard/stiff", "コウ", "かたい", "Size & Quality"),
    _k("美", "beauty", "ビ", "うつくしい", "Size & Quality"),
    _k("定", "decide/fix", "テイ", "さだめる", "Abstract Concepts"),
    _k("決", "decide", "ケツ", "きめる", "Abstract Concepts"),
    _k("判", "judge", "ハン", None, "Abstract Concepts"),
    _k("断", "refuse/cut", "ダン", "ことわる", "Abstract Concepts"),
    _k("許", "permit", "キョ", "ゆるす", "Abstract Concepts"),
    _k("罪", "crime", "ザイ", None, "Abstract Concepts"),
    _k("犯", "commit crime", "ハン", "おかす", "Abstract Concepts"),
    _k("防", "prevent", "ボウ", "ふせぐ", "Abstract Concepts"),
    _k("必", "necessary", "ヒツ", "かならず", "Abstract Concepts"),
    _k("要", "need/important", "ヨウ", "いる", "Abstract Concepts"),
    _k("確", "certain", "カク", "たしか", "Abstract Concepts"),
    _k("完", "complete", "カン", None, "Abstract Concepts"),
    _k("成", "become/achieve", "セイ", "なる", "Abstract Concepts"),
    _k("続", "continue", "ゾク", "つずく", "Abstract Concepts"),
    _k("与", "give", "ヨ", "あたえる", None),
    _k("争", "conflict", "ソウ", "あらそう", None),
    _k("交", "exchange", "コウ", "まじる", None),
    _k("介", "mediate", "カイ", None, None),
    _k("仏", "Buddha", "ブツ", "ほとけ", None),
    _k("代", "generation", "ダイ", "かわる", None),
    _k("任", "responsibility", "ニン", "まかせる", None),
    _k("伝", "transmit", "デン", "つたえる", None),
    _k("位", "rank/position", "イ", "くらい", None),
    _k("住", "live/dwell", "ジュウ", "すむ", None),
    _k("例", "example", "レイ", "たとえる", None),
    _k("供", "offer/provide", "キョウ", "そなえる", None),
    _k("価", "value/price", "カ", "あたい", None),
    _k("保", "preserve", "ホ", "たもつ", None),
    _k("信", "believe/trust", "シン", None, None),
    _k("倒", "topple/fall", "トウ", "たおれる", None),
    _k("値", "value", "チ", "あたい", None),
    _k("備", "prepare", "ビ", "そなえる", None),
    _k("債", "debt", "サイ", None, None),
    _k("兵", "soldier", "ヘイ", None, None),
    _k("具", "tool", "グ", None, None),
    _k("典", "ceremony/code", "テン", None, None),
    _k("刺", "pierce/thorn", "シ", "さす", None),
    _k("則", "rule/law", "ソク", None, None),
    _k("割", "divide/ratio", "カツ", "わる", None),
    _k("加", "add", "カ", "くわえる", None),
    _k("助", "help", "ジョ", "たすける", None),
    _k("努", "effort", "ド", "つとめる", None),
    _k("効", "effect", "コウ", "きく", None),
    _k("勧", "recommend", "カン", "すすめる", None),
    _k("化", "change/transform", "カ", "ばける", None),
    _k("協", "cooperate", "キョウ", None, None),
    _k("印", "stamp/mark", "イン", "しるし", None),
    _k("原", "original/plain", "ゲン", "はら", None),
    _k("参", "participate", "サン", "まいる", None),
    _k("及", "reach/and", "キュウ", "およぶ", None),
    _k("反", "anti/oppose", "ハン", "たん", None),
    _k("台", "platform", "ダイ", "たい", None),
    _k("史", "history", "シ", None, None),
    _k("合", "fit/combine", "ゴウ", "あう", None),
    _k("否", "deny/or not", "ヒ", "いな", None),
    _k("含", "include", "ガン", "ふくむ", None),
    _k("命", "life/command", "メイ", "いのち", None),
    _k("器", "instrument", "キ", "うつわ", None),
    _k("因", "cause", "イン", None, None),
    _k("団", "group", "ダン", None, None),
    _k("圧", "pressure", "アツ", None, None),
    _k("在", "exist/be", "ザイ", "ある", None),
    _k("型", "at model/type", "ケイ", "かた", None),
    _k("域", "area/region", None, "いき", None),
    _k("失", "lose", "シツ", "うしなう", None),
    _k("存", "exist", "ソン", "ぞん", None),
    _k("季", "season", "キ", None, None),
    _k("守", "protect", "シュ", "まもる", None),
    _k("寝", "sleep/lie", "シン", "ねる", None),
    _k("対", "oppose/pair", "タイ", "つい", None),
    _k("導", "guide/lead", "ドウ", "みちびく", None),
    _k("居", "reside", "キョ", "いる", None),
    _k("属", "belong", "ゾク", None, None),
    _k("布", "cloth/spread", "フ", "ぬの", None),
    _k("常", "usual/normal", "ジョウ", "つね", None),
    _k("幅", "width", "フク", "はば", None),
    _k("干", "dry", "カン", "ひる", None),
    _k("平", "flat/peace", "ヘイ", "たいら", None),
    _k("式", "ceremony", "シキ", None, None),
    _k("張", "stretch", "チョウ", "はる", None),
    _k("当", "hit/this", "トウ", "あたる", None),
    _k("形", "shape/form", "ケイ", "かたち", None),
    _k("影", "shadow", "エイ", "かげ", None),
    _k("従", "follow/obey", "ジュウ", "したがう", None),
    _k("得", "gain/obtain", "トク", "える", None),
    _k("忍", "endure", "ニン", "しのぶ", None),
    _k("応", "respond", "オウ", None, None),
    _k("念", "thought/wish", "ネン", None, None),
    _k("性", "nature/gender", "セイ", "しょう", None),
    _k("想", "imagine", "ソウ", None, None),
    _k("態", "attitude", "タイ", None, None),
    _k("戦", "war/battle", "セン", "いくさ", None),
    _k("打", "hit/strike", "ダ", "うつ", None),
    _k("技", "skill", "ギ", "わざ", None),
    _k("抗", "resist", "コウ", None, None),
    _k("抜", "pull out", "バツ", "ぬく", None),
    _k("抵", "resist", "テイ", None, None),
    _k("抽", "extract", "チュウ", None, None),
    _k("担", "bear/carry", "タン", "かつぐ", None),
    _k("捕", "catch", "ホ", "とらえる", None),
    _k("探", "search", "タン", "さぐる", None),
    _k("接", "connect", "セツ", "つぐ", None),
    _k("掲", "display", "ケイ", "かかげる", None),
    _k("換", "exchange", "カン", "かえる", None),
    _k("撮", "photograph", "サツ", "とる", None),
    _k("救", "rescue", "キュウ", "すくう", None),
    _k("敗", "defeat", "ハイ", "やぶれる", None),
    _k("散", "scatter", "サン", "ちる", None),
    _k("数", "number/count", "スウ", "かぞえる", None),
    _k("整", "arrange", "セイ", "ととのえる", None),
    _k("方", "direction/way", "ホウ", "かた", None),
    _k("望", "hope/wish", "ボウ", "のぞむ", None),
    _k("期", "period", "キ", "ご", None),
    _k("札", "tag/bill", "サツ", "ふだ", None),
    _k("束", "bundle", "ソク", "たば", None),
    _k("条", "article/clause", "ジョウ", None, None),
    _k("松", "pine", "ショウ", "まつ", None),
    _k("板", "board/plate", "ハン", "いた", None),
    _k("果", "fruit/result", "カ", "はたす", None),
    _k("柱", "pillar", "チュウ", "はしら", None),
    _k("査", "inspect", "サ", None, None),
    _k("株", "stock/share", None, "かぶ", None),
    _k("格", "status", "カク", None, None),
    _k("械", "machine", "カイ", None, None),
    _k("機", "machine/chance", "キ", None, None),
    _k("次", "next", "ジ", "つぎ", None),
    _k("欺", "deceive", "ギ", "あざむく", None),
    _k("武", "military", "ブ", "たけ", None),
    _k("歴", "history", "レキ", None, None),
    _k("残", "remain", "ザン", "のこる", None),
    _k("比", "compare", "ヒ", "くらべる", None),
    _k("求", "request/seek", "キュウ", "もとめる", None),
    _k("況", "situation", "キョウ", None, None),
    _k("泡", "bubble", "ホウ", "あわ", None),
    _k("波", "wave", "ハ", "なみ", None),
    _k("活", "life/active", "カツ", None, None),
    _k("派", "faction", "ハ", None, None),
    _k("流", "flow", "リュウ", "ながす", None),
    _k("混", "mix/confuse", "コン", "まぜる", None),
    _k("渡", "cross over", "ト", "わたる", None),
    _k("準", "standard", "ジュン", None, None),
    _k("煙", "smoke", "エン", "けむり", None),
    _k("照", "illuminate", "ショウ", "てらす", None),
    _k("状", "condition", "ジョウ", None, None),
    _k("獲", "capture", "カク", "える", None),
    _k("率", "rate/ratio", "リツ", "そつ", None),
    _k("用", "use", "ヨウ", "もちいる", None),
    _k("由", "reason/from", "ユウ", "よし", None),
    _k("申", "say/apply", "シン", "もうす", None),
    _k("留", "stay/fasten", "リュウ", "とめる", None),
    _k("略", "abbreviation", "リャク", None, None),
    _k("疑", "doubt", "ギ", "うたがう", None),
    _k("的", "target", "テキ", "まと", None),
    _k("直", "direct/fix", "チョク", "なおす", None),
    _k("眠", "sleep", "ミン", "ねむる", None),
    _k("睡", "sleep", "スイ", None, None),
    _k("破", "break/tear", "ハ", "やぶる", None),
    _k("礼", "manners/thanks", "レイ", None, None),
    _k("祝", "celebrate", "シュク", "いわう", None),
    _k("神", "god/spirit", "シン", "かみ", None),
    _k("票", "vote/ballot", "ヒョウ", None, None),
    _k("祭", "festival", "サイ", "まつり", None),
    _k("秀", "excel", "シュウ", "ひいでる", None),
    _k("科", "science/section", "カ", None, None),
    _k("秘", "secret", "ヒ", "ひみつ", None),
    _k("程", "extent/degree", "テイ", "ほど", None),
    _k("積", "pile up/area", "セキ", "つむ", None),
    _k("突", "sudden", "トツ", "つく", None),
    _k("競", "compete", "キョウ", "きそう", None),
    _k("等", "equal/etc", "トウ", "など", None),
    _k("管", "pipe/control", "カン", "くだ", None),
    _k("箱", "box", "ソウ", "はこ", None),
    _k("節", "season/joint", "セツ", "ふし", None),
    _k("範", "model/scope", "ハン", None, None),
    _k("約", "promise/about", "ヤク", None, None),
    _k("納", "pay/supply", "ノウ", "おさめる", None),
    _k("累", "accumulate", "ルイ", "かさねる", None),
    _k("紹", "introduce", "ショウ", None, None),
    _k("組", "group", "ソ", "くみ", None),
    _k("結", "tie/conclude", "ケツ", "むすぶ", None),
    _k("統", "unite", "トウ", "すべる", None),
    _k("絵", "picture", "カイ", "え", None),
    _k("絶", "sever", "ゼツ", "たえる", None),
    _k("継", "inherit", "ケイ", "つぐ", None),
    _k("緒", "cord/beginning", "ショ", "お", None),
    _k("線", "line", "セン", None, None),
    _k("織", "weave", "ショク", "おる", None),
    _k("置", "place/put", "チ", "おく", None),
    _k("羽", "feather", "ウ", "はね", None),
    _k("能", "ability", "ノウ", None, None),
    _k("腐", "rot/decay", "フ", "くさる", None),
    _k("著", "author/famous", "チョ", None, None),
    _k("蒸", "steam", "ジョウ", "むす", None),
    _k("術", "art/technique", "ジュツ", None, None),
    _k("衣", "clothing", "イ", "ころも", None),
    _k("袋", "bag", "タイ", "ふくろ", None),
    _k("被", "receive/wear", "ヒ", "こうむる", None),
    _k("装", "equip/pretend", "ソウ", "よそおう", None),
    _k("補", "supplement", "ホ", "おぎなう", None),
    _k("複", "duplicate", None, "ふく", None),
    _k("規", "standard/rule", "キ", None, None),
    _k("観", "view/observe", "カン", None, None),
    _k("角", "angle/horn", "カク", "つの", None),
    _k("解", "solve/untie", "カイ", "とく", None),
    _k("触", "touch", "ショク", "ふれる", None),
    _k("設", "establish", "セツ", "もうける", None),
    _k("詩", "poem", "シ", None, None),
    _k("誤", "mistake", "ゴ", "あやまる", None),
    _k("謝", "thank/apologize", "シャ", "あやまる", None),
    _k("象", "elephant/image", "ショウ", "ぞう", None),
    _k("負", "lose/bear", "フ", "まける", None),
    _k("貨", "goods/currency", "カ", None, None),
    _k("責", "responsibility", "セキ", "せめる", None),
    _k("賀", "congratulate", "ガ", None, None),
    _k("贋", "approve", "サン", None, None),
    _k("贈", "present/gift", "ゾウ", "おくる", None),
    _k("起", "wake/rise", "キ", "おきる", None),
    _k("越", "exceed", "エツ", "こす", None),
    _k("路", "road/path", "ロ", "みち", None),
    _k("軍", "army", "グン", None, None),
    _k("載", "publish/load", "サイ", "のせる", None),
    _k("輪", "wheel/ring", "リン", "わ", None),
    _k("辞", "resign", "ジ", "やめる", None),
    _k("追", "chase", "ツイ", "おう", None),
    _k("途", "route", "ト", None, None),
    _k("造", "create/build", "ゾウ", "つくる", None),
    _k("連", "connect", "レン", "つれる", None),
    _k("遊", "play", "ユウ", "あそぶ", None),
    _k("過", "pass/exceed", "カ", "すぎる", None),
    _k("達", "reach", None, "たつ", None),
    _k("適", "suitable", "テキ", None, None),
    _k("避", "avoid", "ヒ", "さける", None),
    _k("酒", "alcohol", "シュ", "さけ", None),
    _k("釈", "explain", "シャク", None, None),
    _k("量", "quantity", "リョウ", "はかる", None),
    _k("針", "needle", "シン", "はり", None),
    _k("鉄", "iron", "テツ", None, None),
    _k("銀", "silver", "ギン", None, None),
    _k("関", "relate", "カン", "せき", None),
    _k("限", "limit", "ゲン", "かぎる", None),
    _k("際", "occasion", "サイ", "きわ", None),
    _k("雑", "miscellaneous", "ザツ", None, None),
    _k("静", "quiet", "セイ", "しずか", None),
    _k("非", "non/fault", "ヒ", None, None),
    _k("面", "face/surface", "メン", "おもて", None),
    _k("革", "leather/reform", "カク", "かわ", None),
    _k("響", "echo", "キョウ", "ひびく", None),
    _k("領", "territory", "リョウ", None, None),
    _k("額", "amount", "ガク", "ひたい", None),
    _k("願", "wish", "ガン", "ねがう", None),
    _k("飛", "fly", "ヒ", "とぶ", None),
    _k("首", "neck/head", "シュ", "くび", None),
)
