"""JLPT N4 kanji seed data.

Extracted from the Mensura Media reference chart
``japanese/jp_kanji/reference_chart_kanji_n4.pdf`` in the companion
`language-learning <https://github.com/MensuraMedia/language-learning>`_ repository,
which is the authority for this project's character data.

On'yomi are written in katakana and kun'yomi in hiragana, matching the
convention fixed by the content model. The charts give readings in wapuro
romaji; conversion to kana is mechanical and every reading was verified by
converting back and comparing. Where a chart states only one reading it does
not say which kind it is, so the field is chosen from a lexicon built from the
664 explicit on/kun pairs across all five levels — a held-out test of that
rule against the N1 pairs scored 94.6%. **Kanji cards are graded on the
meaning**, so a mislabelled reading affects the reference rows on the card
back and nothing that is scored.

Kun'yomi are the chart's whole-word readings; okurigana are not bracketed as
they are in :mod:`.kanji_n5`. Stroke counts are not in the charts and are left
unset.
"""

from __future__ import annotations

from ..models import CharacterSeed

__all__ = ["KANJI_N4"]


def _k(
    glyph: str,
    meaning: str,
    onyomi: str | None,
    kunyomi: str | None,
    category: str | None,
) -> CharacterSeed:
    """Build a N4 kanji seed with the shared script/level fields filled in."""
    return CharacterSeed(
        glyph=glyph,
        script="kanji",
        meaning=meaning,
        onyomi=onyomi,
        kunyomi=kunyomi,
        jlpt_level="N4",
        category=category,
    )


#: 169 characters, in chart order.
KANJI_N4: tuple[CharacterSeed, ...] = (
    _k("兄", "older brother", "ケイ", "あに", "Family & Relationships"),
    _k("姉", "older sister", "シ", "あね", "Family & Relationships"),
    _k("弟", "younger brother", "テイ", "おとうと", "Family & Relationships"),
    _k("妹", "younger sister", "マイ", "いもうと", "Family & Relationships"),
    _k("親", "parent", "シン", "おや", "Family & Relationships"),
    _k("夫", "husband", "フ", "おっと", "Family & Relationships"),
    _k("妻", "wife", "サイ", "つま", "Family & Relationships"),
    _k("家", "house/home", "カ", "いえ", "Family & Relationships"),
    _k("族", "tribe/family", "ゾク", None, "Family & Relationships"),
    _k("自", "self", "ジ", "みずから", "Family & Relationships"),
    _k("体", "body", "タイ", "からだ", "Body & Health"),
    _k("頭", "head", "トウ", "あたま", "Body & Health"),
    _k("顔", "face", "ガン", "かお", "Body & Health"),
    _k("声", "voice", "セイ", "こえ", "Body & Health"),
    _k("心", "heart/mind", "シン", "こころ", "Body & Health"),
    _k("力", "power/force", "リョク", "ちから", "Body & Health"),
    _k("病", "illness", "ビョウ", "やまい", "Body & Health"),
    _k("医", "medicine/doctor", "イ", None, "Body & Health"),
    _k("薬", "medicine/drug", "ヤク", "くすり", "Body & Health"),
    _k("死", "death/die", "シ", "しぬ", "Body & Health"),
    _k("春", "spring", "シュン", "はる", "Seasons & Time of Day"),
    _k("夏", "summer", "カ", "なつ", "Seasons & Time of Day"),
    _k("秋", "autumn", "シュウ", "あき", "Seasons & Time of Day"),
    _k("冬", "winter", "トウ", "ふゆ", "Seasons & Time of Day"),
    _k("朝", "morning", "チョウ", "あさ", "Seasons & Time of Day"),
    _k("昼", "noon/daytime", "チュウ", "ひる", "Seasons & Time of Day"),
    _k("夜", "night", "ヤ", "よる", "Seasons & Time of Day"),
    _k("明", "bright/clear", "メイ", "あかるい", "Seasons & Time of Day"),
    _k("暗", "dark", "アン", "くらい", "Seasons & Time of Day"),
    _k("海", "sea/ocean", "カイ", "うみ", "Nature & Elements"),
    _k("池", "pond", "チ", "いけ", "Nature & Elements"),
    _k("地", "ground/earth", "チ", "じ", "Nature & Elements"),
    _k("野", "field/plain", "ヤ", "の", "Nature & Elements"),
    _k("林", "grove/forest", "リン", "はやし", "Nature & Elements"),
    _k("森", "forest", "シン", "もり", "Nature & Elements"),
    _k("石", "stone/rock", "セキ", "いし", "Nature & Elements"),
    _k("風", "wind", "フウ", "かぜ", "Nature & Elements"),
    _k("雪", "snow", "セツ", "ゆき", "Nature & Elements"),
    _k("光", "light", "コウ", "ひかり", "Nature & Elements"),
    _k("市", "city/market", "シ", "いち", "Places & Geography"),
    _k("町", "town", "チョウ", "まち", "Places & Geography"),
    _k("村", "village", "ソン", "むら", "Places & Geography"),
    _k("区", "ward/district", "ク", None, "Places & Geography"),
    _k("県", "prefecture", "ケン", None, "Places & Geography"),
    _k("京", "capital", "キョウ", "けい", "Places & Geography"),
    _k("都", "capital/metropolis", "ト", "みやこ", "Places & Geography"),
    _k("世", "world/generation", "セ", "よ", "Places & Geography"),
    _k("界", "world/boundary", "カイ", None, "Places & Geography"),
    _k("場", "place/field", "ジョウ", "ば", "Places & Geography"),
    _k("室", "room", "シツ", "むろ", "Places & Geography"),
    _k("館", "building/hall", "カン", None, "Places & Geography"),
    _k("院", "institution", "イン", None, "Places & Geography"),
    _k("門", "gate", "モン", "かど", "Places & Geography"),
    _k("広", "wide/spacious", "コウ", "ひろい", "Places & Geography"),
    _k("走", "run", "ソウ", "はしる", "Movement & Actions"),
    _k("歩", "walk", "ホ", "あるく", "Movement & Actions"),
    _k("止", "stop", "シ", "とまる", "Movement & Actions"),
    _k("動", "move", "ドウ", "うごく", "Movement & Actions"),
    _k("乗", "ride/board", "ジョウ", "のる", "Movement & Actions"),
    _k("送", "send", "ソウ", "おくる", "Movement & Actions"),
    _k("通", "pass through", "ツウ", "とおる", "Movement & Actions"),
    _k("運", "carry/luck", "ウン", "はこぶ", "Movement & Actions"),
    _k("引", "pull/draw", "イン", "ひく", "Movement & Actions"),
    _k("押", "push", "オウ", "おす", "Movement & Actions"),
    _k("開", "open", "カイ", "ひらく", "Movement & Actions"),
    _k("作", "make/create", "サク", "つくる", "Daily Actions"),
    _k("使", "use", "シ", "つかう", "Daily Actions"),
    _k("持", "hold/have", "ジ", "もつ", "Daily Actions"),
    _k("待", "wait", "タイ", "まつ", "Daily Actions"),
    _k("売", "sell", "バイ", "うる", "Daily Actions"),
    _k("借", "borrow", "シャク", "かりる", "Daily Actions"),
    _k("貸", "lend", "タイ", "かす", "Daily Actions"),
    _k("返", "return/give", "ヘン", "かえす", "Daily Actions"),
    _k("払", "back pay", "フツ", "はらう", "Daily Actions"),
    _k("切", "cut", "セツ", "きる", "Daily Actions"),
    _k("洗", "wash", "セン", "あらう", "Daily Actions"),
    _k("知", "know", "チ", "しる", "Thinking & Learning"),
    _k("思", "think", "シ", "おもう", "Thinking & Learning"),
    _k("考", "consider", "コウ", "かんがえる", "Thinking & Learning"),
    _k("教", "teach", "キョウ", "おしえる", "Thinking & Learning"),
    _k("習", "learn/practice", "シュウ", "ならう", "Thinking & Learning"),
    _k("研", "polish/research", "ケン", "とぐ", "Thinking & Learning"),
    _k("究", "investigate", "キュウ", "きわめる", "Thinking & Learning"),
    _k("問", "question/ask", "モン", "とう", "Thinking & Learning"),
    _k("答", "answer", "トウ", "こたえる", "Thinking & Learning"),
    _k("意", "meaning/intention", "イ", None, "Thinking & Learning"),
    _k("味", "taste/flavor", "ミ", "あじ", "Thinking & Learning"),
    _k("太", "thick/fat", "タイ", "ふとい", "Size & Quality"),
    _k("細", "thin/narrow", "サイ", "ほそい", "Size & Quality"),
    _k("強", "strong", "キョウ", "つよい", "Size & Quality"),
    _k("弱", "weak", "ジャク", "よわい", "Size & Quality"),
    _k("重", "heavy", "ジュウ", "おもい", "Size & Quality"),
    _k("軽", "light weight", "ケイ", "かるい", "Size & Quality"),
    _k("近", "near", "キン", "ちかい", "Size & Quality"),
    _k("遠", "far", "エン", "とおい", "Size & Quality"),
    _k("遅", "slow/late", "チ", "おそい", "Size & Quality"),
    _k("速", "fast/speed", "ソク", "はやい", "Size & Quality"),
    _k("悪", "bad/evil", "アク", "わるい", "Size & Quality"),
    _k("正", "correct/right", "セイ", "ただしい", "Size & Quality"),
    _k("若", "young", "ジャク", "わかい", "Size & Quality"),
    _k("牛", "cow", "ギュウ", "うし", "Animals"),
    _k("馬", "horse", "バ", "うま", "Animals"),
    _k("肉", "meat", "ニク", None, "Animals"),
    _k("英", "English/excellent", "エイ", None, "Abstract & Communication"),
    _k("漢", "kanji/China", "カン", None, "Abstract & Communication"),
    _k("文", "sentence/writing", "ブン", "もん", "Abstract & Communication"),
    _k("紙", "paper", "シ", "かみ", "Abstract & Communication"),
    _k("記", "record/write", "キ", "しるす", "Abstract & Communication"),
    _k("説", "explain/theory", "セツ", "とく", "Abstract & Communication"),
    _k("計", "measure/plan", "ケイ", "はかる", "Abstract & Communication"),
    _k("全", "of all/whole", "ゼン", "まったく", "Abstract & Communication"),
    _k("部", "part/section", "ブ", None, "Abstract & Communication"),
    _k("員", "member", "イン", None, "Abstract & Communication"),
    _k("番", "number/turn", "バン", None, "Abstract & Communication"),
    _k("号", "number/issue", "ゴウ", None, "Abstract & Communication"),
    _k("色", "color", "ショク", "いろ", "Abstract & Communication"),
    _k("音", "sound", "オン", "おと", "Abstract & Communication"),
    _k("変", "change/strange", "ヘン", "かわる", "Abstract & Communication"),
    _k("主", "master/main", "シュ", "ぬし", None),
    _k("彼", "he/that", "ヒ", "かれ", None),
    _k("黒", "black", "コク", "くろい", None),
    _k("黄", "yellow", "オウ", "き", None),
    _k("屋", "shop/roof", "オク", "や", None),
    _k("堂", "hall/temple", "ドウ", None, None),
    _k("届", "deliver/reach", None, "とどく", None),
    _k("閉", "close/shut", "ヘイ", "しめる", None),
    _k("始", "begin/start", "シ", "はじめる", None),
    _k("終", "end/finish", "シュウ", "おわる", None),
    _k("集", "gather/collect", "シュウ", "あつめる", None),
    _k("座", "sit", "ザ", "すわる", None),
    _k("消", "erase/turn", "ショウ", "けす", None),
    _k("着", "off arrive/wear", "チャク", "きる", None),
    _k("歌", "sing/song", "カ", "うたう", None),
    _k("映", "reflect/movie", "エイ", "うつる", None),
    _k("画", "picture/draw", "ガ", "かく", None),
    _k("写", "copy/photo", "シャ", "うつす", None),
    _k("真", "true/real", "シン", "ま", None),
    _k("特", "special", "トク", None, None),
    _k("別", "separate/special", "ベツ", "わかれる", None),
    _k("同", "same", "ドウ", "おなじ", None),
    _k("不", "not/un-", "フ", "ぶ", None),
    _k("便", "convenience", "ベン", "びん", None),
    _k("利", "profit/benefit", "リ", None, None),
    _k("急", "hurry/urgent", "キュウ", "いそぐ", None),
    _k("忙", "busy", "ボウ", "いそがしい", None),
    _k("楽", "fun/music", "ラク", "がく", None),
    _k("有", "exist/have", "ユウ", "ある", None),
    _k("無", "nothing/without", "ム", "ない", None),
    _k("飯", "meal/rice", "ハン", "めし", None),
    _k("茶", "tea", "チャ", "さ", None),
    _k("料", "fee/material", "リョウ", None, None),
    _k("理", "reason/logic", "リ", None, None),
    _k("工", "construction", "コウ", "く", None),
    _k("業", "business/work", "ギョウ", "わざ", None),
    _k("産", "produce/birth", "サン", "うむ", None),
    _k("品", "goods/quality", "ヒン", "しな", None),
    _k("物", "thing/object", "ブツ", "もの", None),
    _k("服", "clothes", None, "ふく", None),
    _k("質", "quality", "シツ", "しち", None),
    _k("題", "topic/title", "ダイ", None, None),
    _k("試", "try/test", "シ", "こころみる", None),
    _k("験", "experience/test", "ケン", None, None),
    _k("度", "degree/time", "ド", "たび", None),
    _k("回", "turn/times", "カイ", "まわる", None),
    _k("転", "roll/turn", "テン", "ころがる", None),
    _k("以", "by means", "イ", None, None),
    _k("注", "pour/attention", "チュウ", "そそぐ", None),
    _k("発", "emit/depart", "ハツ", None, None),
    _k("去", "leave/past", "キョ", "さる", None),
)
